name: Local CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Trigger on push to main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Script
        run: python main.py  # Execute your script

      - name: Verify Output
        run: |
          $output = python main.py
          if ($output -match "CI CD Pipeline test in git hub actions") {
            echo "✅ Script executed successfully!"
          } else {
            echo "❌ Output did not match expected result."
            exit 1
          }


  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Local Path
        run: |
          echo "Starting local deployment on Windows..."
          
          $PROJECT_PATH="C:\Users\vivek\PycharmProjects\CI_CD_Test"
          echo "Deploying to: $PROJECT_PATH"
          
          if (-Not (Test-Path $PROJECT_PATH)) { New-Item -ItemType Directory -Path $PROJECT_PATH }
          
          Copy-Item -Path main.py -Destination $PROJECT_PATH -Force
          
          echo "✅ Deployment completed successfully."

      - name: Run Deployed Script
        run: |
          cd C:\Users\vivek\PycharmProjects\CI_CD_Test
          python main.py  # Run script after deployment
