name: Local CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Trigger on push to main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Local Path
        run: |
          echo "Starting local deployment on Windows..."
          
          
          $PROJECT_PATH="C:\Users\vivek\PycharmProjects\CI_CD_Test\build\CI_CD_Test_Latest_Build"
          
          $TIMESTAMP = Get-Date -Format "dd_MM_yyyy_HH_mm_ss"
          $BACKUP_PROJECT_PATH="C:\Users\vivek\PycharmProjects\CI_CD_Test\backups_build\CI_CD_Test_pushed_by_${{ github.actor }}_${TIMESTAMP}"
          echo "Deploying to: $PROJECT_PATH"
          
          if (-Not (Test-Path $PROJECT_PATH)) { New-Item -ItemType Directory -Path $PROJECT_PATH }
          
          Copy-Item -Path * -Destination $PROJECT_PATH -Force
          Copy-Item -Path * -Destination $BACKUP_PROJECT_PATH -Force
          
          echo "✅ Deployment completed successfully."

      - name: Run Deployed Script
        run: |
          cd C:\Users\vivek\PycharmProjects\CI_CD_Test\build\CI_CD_Test_Latest_Build
          python main.py  # Run script after deployment
